### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by Akanksha2391**
Issue: 4

#### Short description of what this resolves:
Added my name to the contributors and created setup locally

#### Changes proposed in this pull request and/or Screenshots of changes:
Screenshot (195)

### CODE REVIEW

**Comment by homewardgamer** [comment]
Resolve the merge conflicts @Akanksha2391

**Comment by Akanksha2391** [comment]
@homewardgamer done sir

**Comment by homewardgamer** [comment]
Add your name to the bottom of the list. @Akanksha2391

**Comment by Akanksha2391** [comment]
@homewardgamer done

**Pull request merged**
