### PR TITLE
Setup done

### PR DESCRIPTION
**Pull request by asingh1601**
Issue: 4 

Short description of what this resolves:
Setup of project on local machine

 Changes proposed in this pull request and/or Screenshots of changes:
ss

-
-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
Remove the # before the Issue number, it should be like this `Issue: 4`. Also resolve the merge conflicts. @asingh1601

**Comment by asingh1601** [comment]
is it okay now ?

**Comment by homewardgamer** [comment]
Merge conflicts still not resolved. @asingh1601

**Comment by asingh1601** [comment]
[CONTRIBUTORS.md](https://github.com/opencodeiiita/Geek-Chat/files/7277009/CONTRIBUTORS.md)

**Comment by homewardgamer** [comment]
add new changes to the PR not on the comment section. @asingh1601

**Comment by asingh1601** [comment]
I created a new pull request sir please look on it

**Pull request closed without merging**
