### PR TITLE
Updated Contributers.md and setup the project

### PR DESCRIPTION
**Pull request by Siddharth1002**
Issue: 4

#### Short description of what this resolves:
- Setup the given project. 
- Installed npm and all the required deependencies
- website hosted on localhost at port 3000

#### Changes proposed in this pull request and/or Screenshots of changes:
image

-
-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
You have changed the `package-lock.json` file.Revert those changes @Siddharth1002

**Comment by Siddharth1002** [comment]
> You have changed the `package-lock.json` file.Revert those changes @Siddharth1002

ok

**Comment by homewardgamer** [comment]
You reverted the CONTRIBUTORS.md file changes too. @Siddharth1002. Correct that and your pr will be merged.

**Comment by Siddharth1002** [comment]
Too many pr's.

**Pull request closed without merging**
