### PR TITLE
improved frontpage

### PR DESCRIPTION
**Pull request by varunKT001**
Issue: 254

#### Short description of what this resolves:
changed the design of frontpage

#### Changes proposed in this pull request and/or Screenshots of changes:
(also changed the input focus effect)

image
image

## Live Link : [https://opencode-geekchat-demo.herokuapp.com/](https://opencode-geekchat-demo.herokuapp.com/)

-
-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
Not aligned perfectly in mobile view @varunKT001

**Comment by varunKT001** [comment]
> Not aligned perfectly in mobile view @varunKT001

ohh, I just forgot to do for mobile view 😅 will fix it asap

**Comment by varunKT001** [comment]
@homewardgamer fixed the alignment for mobile devices 
image
image
image

**Comment by varunKT001** [comment]
@homewardgamer sir any extra points for some efforts on the hover effects, you said in the issue 😅

**Pull request merged**
