### PR TITLE
Styled the messages sent and received differently

### PR DESCRIPTION
**Pull request by shlesh**
Issue: 156

#### Short description of what this resolves:
Sent and recieved messages now appear different

#### Changes proposed in this pull request and/or Screenshots of changes:

image
image

### CODE REVIEW

**Comment by homewardgamer** [comment]
> @homewardgamer could you please merge this bro ill do the styling and push it in the next PR

I can't merge PR until the task is 100% done. Complete the styling , squash the commits and then make the PR.

**Comment by shlesh** [comment]
> 
> 
> Like iam saying this becuase ive already edited the code a lot, even the js.. to show the geekchat bot messages differently

ab din me tessri baar conflict sahi karna hoga bro🥺🥺🥺🥺🥺

**Comment by homewardgamer** [comment]
> > 
> > 
> > > @homewardgamer could you please merge this bro ill do the styling and push it in the next PR
> > 
> > I can't merge the PR until the task is 100% done. Complete the styling , squash the commits and then make the PR.
> 
> I understand.... but technically i was just supposed to style the messages differently😉😂😂😂😂
> 
> 
It's a 30 Points issue, the PR submitted should be worth the points. As for the merge conflicts, submit your PR at the earliest to avoid this.

**Comment by shlesh** [comment]
> 
> 
> > > > @homewardgamer could you please merge this bro ill do the styling and push it in the next PR
> > > 
> > > 
> > > I can't merge the PR until the task is 100% done. Complete the styling , squash the commits and then make the PR.
> > 
> > 
> > I understand.... but technically i was just supposed to style the messages differently😉😂😂😂😂
> 
> It's a 30 Points issue, the PR submitted should be worth the points. As for the merge conflicts, submit your PR at the earliest to avoid this.

cool cool gotchya XD

**Comment by shlesh** [comment]
image
image

**Pull request merged**
