### PR TITLE
Upated Contributor.md

### PR DESCRIPTION
**Pull request by pranjalkatiyar**
Issue: 4

Short description of what this resolves:

Setup project in local machine and updated Contributors.md

Changes proposed in this pull request and/or Screenshots of changes:

o

-
-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
resolve merge conflicts and revert the 735 changes made in the `package-lock.json`

**Comment by pranjalkatiyar** [comment]
how can i revert the changes?

**Comment by homewardgamer** [comment]
https://www.freecodecamp.org/news/how-to-undo-changes-in-git-e1da7930afdb/ 

> how can i revert the changes?

**Comment by pranjalkatiyar** [comment]
@homewardgamer can you pls check is it done or not?

**Pull request closed without merging**
