### PR TITLE
Adds niyoj in CONTRIBUTIONS.md file

### PR DESCRIPTION
**Pull request by niyoj**
Issue: 4

#### Short description of what this resolves:
The issue is to setup the project in the local system and add your name in `CONTRIBUTION.md` file.

#### Changes proposed in this pull request and/or Screenshots of changes:

- Inside `./CONTRIBUTION.md` file a new line was added for `niyoj`.
- The project setup was done and the website was successfully running on `localhost:3000`.
- The screenshot after the setup is below;
Screenshot from 2021-10-06 07-41-10

### CODE REVIEW

**Comment by homewardgamer** [comment]
Resolve merge conflicts @niyoj

**Comment by niyoj** [comment]
Ok will do that

**Comment by niyoj** [comment]
Done. Should I squash the commit too?

**Comment by homewardgamer** [comment]
no need to squash, delete line no`74`. @niyoj

**Comment by niyoj** [comment]
@homewardgamer Done.

**Comment by niyoj** [comment]
Now everything is resolved

**Pull request merged**
