### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by saisumanthkumar**
Issue: 4

#### Short description of what this resolves:

setup this project on local machine and added myself to CONTRIBUTERS.md

#### Changes proposed in this pull request and/or Screenshots of changes
Screenshot (142)

### CODE REVIEW

**Comment by homewardgamer** [comment]
You are not registered on devfolio
Contact the organisers for this

**Comment by saisumanthkumar** [comment]
@homewardgamer I have registered in devfolio

**Comment by homewardgamer** [comment]
check the leaderboard. Your score is updated. @saisumanthkumar

**Comment by saisumanthkumar** [comment]
ok,thank you @homewardgamer

**Pull request merged**
