### PR TITLE
Added name in CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by codelord09**
Issue: 4

Short description of what this resolves:
Added my GitHub in CONTRIBUTORS.md File and also did the project set up

Changes proposed in this pull request and/or Screenshots of changes:

#### Short description of what this resolves:
image

### CODE REVIEW

**Comment by homewardgamer** [comment]
Resolve merge conflicts @codelord09

**Comment by homewardgamer** [comment]
Resolve merge conflicts @codelord09

**Comment by codelord09** [comment]
Hey @homewardgamer ,
Kindly check now

**Comment by homewardgamer** [comment]
add your name to the bottom of the list @codelord09

**Pull request merged**
