### PR TITLE
Updates CONTRIBUTERS.md

### PR DESCRIPTION
**Pull request by janhaviiii**
Issue: 4

#### Short description of what this resolves: 
Added name in CONTRIBUTERS.md 

#### Changes proposed in this pull request and/or Screenshots of changes:

Screenshot (530)

### CODE REVIEW

**Comment by homewardgamer** [comment]
resolve merge conflict @janhaviiii

**Comment by homewardgamer** [comment]
Add your name to the end of the list @janhaviiii

**Comment by janhaviiii** [comment]
@homewardgamer  add this pull request

**Comment by homewardgamer** [comment]
I already merged one Pr from you from this issue right? #69

**Pull request merged**
