### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by Monik09**
Issue: 4

#### Short description of what this resolves:
Added name in contributor.md and setup project locally.

#### Changes proposed in this pull request and/or Screenshots of changes:
image
image

### CODE REVIEW

**Comment by homewardgamer** [comment]
Add a space between : and 4.It should be like this `Issue: 4`. also resolve merge conflicts.

**Comment by Monik09** [comment]
@homewardgamer I have resolved the conflicts and updated the description.

**Comment by homewardgamer** [comment]
Add your name to the bottom of the list @Monik09

**Comment by Monik09** [comment]
@homewardgamer done

**Pull request merged**
