### PR TITLE
setup done #4

### PR DESCRIPTION
**Pull request by medhatiwari**
Issue: 4

#### Short description of what this resolves:
- Setup
- Added me to contributor's list

#### Changes proposed in this pull request and/or Screenshots of changes:

Screenshot 2021-10-05 163220

### CODE REVIEW

**Comment by homewardgamer** [comment]
1250 changes in the `package-lock.json`. Revert them

**Comment by medhatiwari** [comment]
> 1250 changes in the `package-lock.json`. Revert them

So I have to delete the package-lock.json? Right?

**Comment by homewardgamer** [comment]
Try closing this PR and forking the repo again since the changes are still there. @medhatiwari

**Comment by medhatiwari** [comment]
> Try closing this PR and forking the repo again since the changes are still there. @medhatiwari 

Alright

**Pull request closed without merging**
