### PR TITLE
Added my name in CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by mayank-kr**
Issue: 4

#### Short description of what this resolves:

added myself in CONTRIBUTORS.md

#### Changes proposed in this pull request and/or Screenshots of changes:
Screenshot (567)

### CODE REVIEW

**Comment by homewardgamer** [comment]
Add your name to the bottom of the list @mayank-kr

**Comment by homewardgamer** [comment]
Resolve merge conflicts @mayank-kr

**Comment by mayank-kr** [comment]
> Resolve merge conflicts @mayank-kr

Actually when I resolve conflict, by the time I have merged it someone else's pr is getting accepted due to which its again asking to resolve conflicts

**Comment by homewardgamer** [comment]
> > Resolve merge conflicts @mayank-kr
> 
> Actually when I resolve conflict, by the time I have merged it someone else's pr is getting accepted due to which its again asking to resolve conflicts

I know this issue comes, but whoever solves the merge conflict first gets their Pr merged

**Pull request merged**
