### PR TITLE
Issue: 4

### PR DESCRIPTION
**Pull request by karankc23**
Issue: 4

Short description of what this resolves:

set up the project at my system and added my name in contributors.md file

Changes proposed in this pull request and/or Screenshots of changes:

geek-chat local host

-
-
-

### CODE REVIEW

**Comment by karankc23** [comment]
@homewardgamer please merge this

**Comment by homewardgamer** [comment]
Resolve merge conflicts @karankc23

**Comment by karankc23** [comment]
@homewardgamer i resolved the merge conflict please check it now

**Comment by homewardgamer** [comment]
Add your name to the bottom of the list @karankc23

**Comment by karankc23** [comment]
@homewardgamer should i close this PR and open a new PR?

**Comment by homewardgamer** [comment]
No need for that you can make changes here only @karankc23

**Comment by karankc23** [comment]
it was not working this way, so i had made a new PR

**Pull request closed without merging**
