### PR TITLE
Make Front Page Responsive

### PR DESCRIPTION
**Pull request by batflarrow**
Issue: 3

#### Short description of what this resolves:
Made the front page responsive

#### Changes proposed in this pull request and/or Screenshots of changes:

- https://geek-chat-batflarrow.herokuapp.com/
-
-

### CODE REVIEW

**Comment by batflarrow** [comment]
@homewardgamer Let me know if any changes are required.

**Comment by homewardgamer** [comment]
Issues in the PR: @batflarrow 
- At 320 x 480 resolution the Join button overflows
- For a normal mobile view, the Username, Join room are not centered in the outer div.
- The animation becomes too small in mobile view.
I have attached some screenshots for this too.
Screen Shot 2021-10-09 at 13 01 01

**Comment by batflarrow** [comment]
- It isn't overflowing in in 320*480 now
image
- Increased size of the animation in mobile view and content looks centered now in mobile
image

 @homewardgamer Can you review it..?

**Comment by homewardgamer** [comment]
Few other changes that can be done are
- The chatting page is not centered and give it a minimum height before the content starts
- In the main page the div can be made longer and more spacing can be given between the content in the div
- The GeekChat main heading should be larger than the text in the div
Since it's a 30 Points Issue I have to be a little strict in this one.
Screen Shot 2021-10-09 at 14 56 06

**Comment by batflarrow** [comment]
> Few other changes that can be done are @batflarrow 
> - The chatting page is not centered and give it a minimum height before the content starts
> - In the main page the div can be made longer and more spacing can be given between the content in the div
> - The GeekChat main heading should be larger than the text in the div
> Since it's a 30 Points Issue I have to be a little strict in this one.
> Screen Shot 2021-10-09 at 14 56 06
> 

Ohk I'll take a look at it i didn't know i had to make changes to chat screen too..

**Comment by batflarrow** [comment]
- Increased the size of div and font size 
image
- Centered and set min height
image

@homewardgamer made the requires changes

**Comment by homewardgamer** [comment]
> - Increased the size of div and font size 
> image
> - Centered and set min height
> image
> 
> @homewardgamer made the requires changes

The content is not centered.

**Pull request merged**
