### PR TITLE
Update contributors.md

### PR DESCRIPTION
**Pull request by asingh1601**
Issue: 4

Short description of what this resolves:
Added name in contributors.md

Changes proposed in this pull request and/or Screenshots of changes:
ss

-
-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
Resolve merge conflicts @asingh1601

**Comment by asingh1601** [comment]
Sir I resolve the conflict . Is it okay now ?

**Comment by homewardgamer** [comment]
Add your name to the bottom of the list @asingh1601

**Comment by asingh1601** [comment]
Is it okay now ?

**Pull request merged**
