### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by shreya-0508**
Issue: 4

#### Short description of what this resolves:
added name in contributors and done local setup

#### Changes proposed in this pull request and/or Screenshots of changes:

-
geekchat_shreya

-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
Resolve merge conflicts @shreya-0508

**Comment by shreya-0508** [comment]
> Resolve merge conflicts @shreya-

**Comment by shreya-0508** [comment]
conflicts has now resolved

**Comment by homewardgamer** [comment]
Add yourself to the end of the list @shreya-0508

**Pull request merged**
