### PR TITLE
e added in contributors.md

### PR DESCRIPTION
**Pull request by A-Spiral-Forge**
Issue: 4
#### Short description of what this resolves:
Added name in contributors.md

#### Changes proposed in this pull request and/or Screenshots of changes:
image

### CODE REVIEW

**Comment by homewardgamer** [comment]
Read the issue carefully You are needed to add the screenshot of the frontpage of the webapp on your local server. @A-Spiral-Forge

**Comment by A-Spiral-Forge** [comment]
> Read the issue carefully You are needed to add the screenshot of the frontpage of the webapp on your local server. @A-Spiral-Forge

@homewardgamer Done ✌✌
image

**Comment by homewardgamer** [comment]
resolve merge conflicts @A-Spiral-Forge

**Comment by A-Spiral-Forge** [comment]
@homewardgamer issue reolved

**Comment by homewardgamer** [comment]
You have 718 changes in the `package-lock.json` file. REvert those changes

**Comment by A-Spiral-Forge** [comment]
@homewardgamer I made a new PR consider that.

**Pull request closed without merging**
