### PR TITLE
Reduced background image size from 541KB to 16KB to reduce loading time

### PR DESCRIPTION
**Pull request by varunKT001**
Issue: 68

#### Short description of what this resolves:
Compressed the background image to reduce loading time. File size reduced from 541KB to 16KB while maintaining the quality. 

#### Changes proposed in this pull request and/or Screenshots of changes:
Original background image: 
image
Compressed background image : 
image

-
-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
This was not the solution I was hoping for @varunKT001. Find a better and more efficient way to do this.

**Comment by varunKT001** [comment]
hey, I came up with a better solution. 
changed the background style from image to a linear gradient. It also removes the background repeating when we zoom out. 

Original : 
image

linear gradient : 
image

**Comment by homewardgamer** [comment]
nicely done @varunKT001 . Now remove the `cool-background (1).png` file since it's no longer needed.

**Comment by varunKT001** [comment]
Sure

**Comment by varunKT001** [comment]
Done 👍. Removed the background image

**Pull request merged**
