### PR TITLE
Updated Contributors list

### PR DESCRIPTION
**Pull request by Atif0604**
Issue: 4

#### Short description of what this resolves:
Added Name in Contributors List

image

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
Read the issue carefully @Atif0604 You are to setup the project also

**Comment by Atif0604** [comment]
> Read the issue carefully @Atif0604 You are to setup the project also

Oops i have done it but forgot to add the screenshot

**Comment by Atif0604** [comment]
hey @homewardgamer i have added the screenshot
Hope its good to go now

**Comment by homewardgamer** [comment]
Resolve the merge conflicts and it's ready to merge. @Atif0604

**Comment by Atif0604** [comment]
sure

**Comment by homewardgamer** [comment]
There are 716 changes in the `package-lock.json`. Revert them.

**Comment by homewardgamer** [comment]
Add your name to the bottom of the list @Atif0604

**Comment by homewardgamer** [comment]
Resolve merge conflicts @Atif0604

**Pull request merged**
