### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by nitheesh96**
Issue: 4

#### Short description of what this resolves:
Added my name to contributers.md
attaching the screen shot of the set up.

#### Changes proposed in this pull request and/or Screenshots of changes:

Screenshot (66)

### CODE REVIEW

**Comment by homewardgamer** [comment]
resolve merge conflict @nitheesh96

**Comment by homewardgamer** [comment]
Add your name to the bottom of the list @nitheesh96

**Comment by nitheesh96** [comment]
Ok

**Comment by nitheesh96** [comment]
added my name at the bottom of the list

**Pull request merged**
