### PR TITLE
added my name to contributors.md

### PR DESCRIPTION
**Pull request by rankit2001**
Issue: 4

Short description of what this resolves:
Added my GitHub in CONTRIBUTORS.md File and also did the project set up

Changes proposed in this pull request and/or Screenshots of changes:

Short description of what this resolves:
rankit2001

### CODE REVIEW

**Comment by homewardgamer** [comment]
Follow the PR template correctly @rankit2001

**Comment by rankit2001** [comment]
check now

**Comment by homewardgamer** [comment]
Resolve the merge conflicts and be sure to add your name to the **end** of the list. @rankit2001

**Comment by rankit2001** [comment]
check now

**Pull request merged**
