### PR TITLE
Add online users

### PR DESCRIPTION
**Pull request by batflarrow**
Issue: 142

#### Short description of what this resolves:
Show online users

#### Changes proposed in this pull request and/or Screenshots of changes:

- https://geek-chat-batflarrow.herokuapp.com/
- Showing online users
- Removing a user from the list of online users when leaving room
- Adding user to list of online users when joining room

### CODE REVIEW

**Comment by batflarrow** [comment]
@homewardgamer Please take a look and let me know if anything is required.

**Comment by batflarrow** [comment]
> Issues in the PR @batflarrow
> 
> * Add a transition to Online users list change, as of now it's abrupt.
> * On load it takes a few seconds to load the Room number and the Online Users, reduce that time or make the loading transition smoother(It's also abrupt).
 
On initial loading shall I add loaders for room names and online users?

**Comment by homewardgamer** [comment]
> > Issues in the PR @batflarrow
> > 
> > * Add a transition to Online users list change, as of now it's abrupt.
> > * On load it takes a few seconds to load the Room number and the Online Users, reduce that time or make the loading transition smoother(It's also abrupt).
> 
> On initial loading shall I add loaders for room names and online users?
Yes you can do that also. @batflarrow

**Comment by batflarrow** [comment]
> One more thing @batflarrow , remove the $ from the variable names starting, since it's not PHP, we can use variable names without the $.

Ohk I had them because I followed a convention to differentiate HTML element nodes from normal variables I will remove them now.

**Comment by batflarrow** [comment]
> Why have you made changes in the .css file only? The guidelines were clear that you are required to change only the .scss files and then compile them to .css. Revert the changes in the css files and do again. @batflarrow

@homewardgamer I made the required changes. Sorry bout the css issue won't happen again.

**Pull request merged**
