### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by yadav-rohit**
Issue: 4

Short description of what this resolves:
setup of project on local machine

Changes proposed in this pull request and/or Screenshots of change:

Screenshot 2021-10-04 121700
s:

### CODE REVIEW

**Comment by homewardgamer** [comment]
resolve the merge conflicts @yadav-rohit

**Comment by yadav-rohit** [comment]
@homewardgamer 
solved sir , have a look

**Comment by homewardgamer** [comment]
@yadav-rohit Add your name to the bottom of the list and please room the screenshot link from the CONTRIBUTORS.md file.

**Comment by homewardgamer** [comment]
Looks good!

**Pull request merged**
