### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by Manthanjain**
Issue: 4

Short description of what this resolves:
Added name to contributors.md file and attaching a screenshot of the project setup done on my local machine.

Changes proposed in this pull request and/or Screenshots of changes:
Geekchat

-
-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
Resolve merge conflicts @Manthanjain

**Comment by Manthanjain** [comment]
@homewardgamer is it okay now?

**Comment by homewardgamer** [comment]
Add your name at the bottom of the list @Manthanjain

**Comment by Manthanjain** [comment]
@homewardgamer is it added now?

**Pull request merged**
